# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'text_spliter_settings_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(304, 378)
        self.gridLayoutWidget = QtWidgets.QWidget(Form)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(49, 70, 201, 281))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.sentenceCheckBox = QtWidgets.QCheckBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.sentenceCheckBox.setFont(font)
        self.sentenceCheckBox.setObjectName("sentenceCheckBox")
        self.gridLayout.addWidget(self.sentenceCheckBox, 1, 0, 1, 1)
        self.paragrafCheckBox = QtWidgets.QCheckBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.paragrafCheckBox.setFont(font)
        self.paragrafCheckBox.setObjectName("paragrafCheckBox")
        self.gridLayout.addWidget(self.paragrafCheckBox, 2, 0, 1, 1)
        self.areaCheckBox = QtWidgets.QCheckBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.areaCheckBox.setFont(font)
        self.areaCheckBox.setObjectName("areaCheckBox")
        self.gridLayout.addWidget(self.areaCheckBox, 3, 0, 1, 1)
        self.wordCheckBox = QtWidgets.QCheckBox(self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.wordCheckBox.setFont(font)
        self.wordCheckBox.setObjectName("wordCheckBox")
        self.gridLayout.addWidget(self.wordCheckBox, 0, 0, 1, 1)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(70, 20, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label.setFont(font)
        self.label.setObjectName("label")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Настройки разбиения текста"))
        self.sentenceCheckBox.setText(_translate("Form", "Предложение"))
        self.paragrafCheckBox.setText(_translate("Form", "Абзац"))
        self.areaCheckBox.setText(_translate("Form", "Области"))
        self.wordCheckBox.setText(_translate("Form", "Слово"))
        self.label.setText(_translate("Form", "Настройки:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
