# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'db_manager_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DB_Form(object):
    def setupUi(self, DB_Form):
        DB_Form.setObjectName("DB_Form")
        DB_Form.resize(649, 389)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(DB_Form.sizePolicy().hasHeightForWidth())
        DB_Form.setSizePolicy(sizePolicy)
        self.label = QtWidgets.QLabel(DB_Form)
        self.label.setGeometry(QtCore.QRect(20, 0, 276, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.delete_table_btn = QtWidgets.QPushButton(DB_Form)
        self.delete_table_btn.setGeometry(QtCore.QRect(410, 120, 201, 28))
        self.delete_table_btn.setObjectName("delete_table_btn")
        self.use_table_btn = QtWidgets.QPushButton(DB_Form)
        self.use_table_btn.setGeometry(QtCore.QRect(410, 70, 201, 28))
        self.use_table_btn.setObjectName("use_table_btn")
        self.create_table_btn = QtWidgets.QPushButton(DB_Form)
        self.create_table_btn.setGeometry(QtCore.QRect(410, 170, 201, 28))
        self.create_table_btn.setObjectName("create_table_btn")

        self.retranslateUi(DB_Form)
        QtCore.QMetaObject.connectSlotsByName(DB_Form)

    def retranslateUi(self, DB_Form):
        _translate = QtCore.QCoreApplication.translate
        DB_Form.setWindowTitle(_translate("DB_Form", "Менеджер баз данных"))
        self.label.setText(_translate("DB_Form", "Доступные таблицы:"))
        self.delete_table_btn.setText(_translate("DB_Form", "Удалить таблицы"))
        self.use_table_btn.setText(_translate("DB_Form", "Использовать таблицы"))
        self.create_table_btn.setText(_translate("DB_Form", "Создать новую таблицу"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DB_Form = QtWidgets.QWidget()
    ui = Ui_DB_Form()
    ui.setupUi(DB_Form)
    DB_Form.show()
    sys.exit(app.exec_())
