# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'select_pos_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PosForm(object):
    def setupUi(self, PosForm):
        PosForm.setObjectName("PosForm")
        PosForm.resize(297, 175)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(PosForm.sizePolicy().hasHeightForWidth())
        PosForm.setSizePolicy(sizePolicy)
        self.spinBox = QtWidgets.QSpinBox(PosForm)
        self.spinBox.setGeometry(QtCore.QRect(180, 50, 42, 22))
        self.spinBox.setObjectName("spinBox")
        self.label = QtWidgets.QLabel(PosForm)
        self.label.setGeometry(QtCore.QRect(60, 40, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.show_let_pos_btn = QtWidgets.QPushButton(PosForm)
        self.show_let_pos_btn.setGeometry(QtCore.QRect(100, 110, 93, 28))
        self.show_let_pos_btn.setObjectName("show_let_pos_btn")

        self.retranslateUi(PosForm)
        QtCore.QMetaObject.connectSlotsByName(PosForm)

    def retranslateUi(self, PosForm):
        _translate = QtCore.QCoreApplication.translate
        PosForm.setWindowTitle(_translate("PosForm", "Выбор позиции"))
        self.label.setText(_translate("PosForm", "Позиция"))
        self.show_let_pos_btn.setText(_translate("PosForm", "Показать"))
