# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'text_analysis_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Text_analisis_form(object):
    def setupUi(self, Text_analisis_form):
        Text_analisis_form.setObjectName("Text_analisis_form")
        Text_analisis_form.resize(757, 343)
        self.centralwidget = QtWidgets.QWidget(Text_analisis_form)
        self.centralwidget.setObjectName("centralwidget")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(10, 0, 731, 301))
        self.textEdit.setObjectName("textEdit")
        Text_analisis_form.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Text_analisis_form)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 757, 21))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        Text_analisis_form.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Text_analisis_form)
        self.statusbar.setObjectName("statusbar")
        Text_analisis_form.setStatusBar(self.statusbar)
        self.action_load_text = QtWidgets.QAction(Text_analisis_form)
        self.action_load_text.setObjectName("action_load_text")
        self.action_text_statistic = QtWidgets.QAction(Text_analisis_form)
        self.action_text_statistic.setObjectName("action_text_statistic")
        self.action_sentence_analyzer = QtWidgets.QAction(Text_analisis_form)
        self.action_sentence_analyzer.setObjectName("action_sentence_analyzer")
        self.action_find_words_by_name_letters = QtWidgets.QAction(Text_analisis_form)
        self.action_find_words_by_name_letters.setObjectName("action_find_words_by_name_letters")
        self.action_first_letter_words = QtWidgets.QAction(Text_analisis_form)
        self.action_first_letter_words.setObjectName("action_first_letter_words")
        self.action_last_letters_words = QtWidgets.QAction(Text_analisis_form)
        self.action_last_letters_words.setObjectName("action_last_letters_words")
        self.action_middle_letters_words = QtWidgets.QAction(Text_analisis_form)
        self.action_middle_letters_words.setObjectName("action_middle_letters_words")
        self.action_split_analizer = QtWidgets.QAction(Text_analisis_form)
        self.action_split_analizer.setObjectName("action_split_analizer")
        self.menu.addAction(self.action_load_text)
        self.menu_2.addAction(self.action_text_statistic)
        self.menu_2.addAction(self.action_sentence_analyzer)
        self.menu_2.addAction(self.action_split_analizer)
        self.menu_2.addAction(self.action_find_words_by_name_letters)
        self.menu_2.addSeparator()
        self.menu_2.addAction(self.action_first_letter_words)
        self.menu_2.addAction(self.action_middle_letters_words)
        self.menu_2.addAction(self.action_last_letters_words)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())

        self.retranslateUi(Text_analisis_form)
        QtCore.QMetaObject.connectSlotsByName(Text_analisis_form)

    def retranslateUi(self, Text_analisis_form):
        _translate = QtCore.QCoreApplication.translate
        Text_analisis_form.setWindowTitle(_translate("Text_analisis_form", "Анализ текста"))
        self.menu.setTitle(_translate("Text_analisis_form", "Файл"))
        self.menu_2.setTitle(_translate("Text_analisis_form", "Анализ"))
        self.action_load_text.setText(_translate("Text_analisis_form", "Загрузить текст"))
        self.action_text_statistic.setText(_translate("Text_analisis_form", "Статистика по тексту"))
        self.action_sentence_analyzer.setText(_translate("Text_analisis_form", "Анализ по предложениям"))
        self.action_find_words_by_name_letters.setText(_translate("Text_analisis_form", "Как текст видит имя"))
        self.action_first_letter_words.setText(_translate("Text_analisis_form", "Слова по первым буквам"))
        self.action_last_letters_words.setText(_translate("Text_analisis_form", "Слова по последним буквам"))
        self.action_middle_letters_words.setText(_translate("Text_analisis_form", "Слова по промежуточным буквам"))
        self.action_split_analizer.setText(_translate("Text_analisis_form", "Анализ с учетом разбиения"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Text_analisis_form = QtWidgets.QMainWindow()
    ui = Ui_Text_analisis_form()
    ui.setupUi(Text_analisis_form)
    Text_analisis_form.show()
    sys.exit(app.exec_())
